(cl:defpackage coalas_pkg-srv
  (:use )
  (:export
   "CHAIRSTATESERVICE"
   "<CHAIRSTATESERVICE-REQUEST>"
   "CHAIRSTATESERVICE-REQUEST"
   "<CHAIRSTATESERVICE-RESPONSE>"
   "CHAIRSTATESERVICE-RESPONSE"
   "COLLAVOIDSERVICE"
   "<COLLAVOIDSERVICE-REQUEST>"
   "COLLAVOIDSERVICE-REQUEST"
   "<COLLAVOIDSERVICE-RESPONSE>"
   "COLLAVOIDSERVICE-RESPONSE"
  ))

