// Generated by gencpp from file coalas_pkg/ChairStateServiceRequest.msg
// DO NOT EDIT!


#ifndef COALAS_PKG_MESSAGE_CHAIRSTATESERVICEREQUEST_H
#define COALAS_PKG_MESSAGE_CHAIRSTATESERVICEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace coalas_pkg
{
template <class ContainerAllocator>
struct ChairStateServiceRequest_
{
  typedef ChairStateServiceRequest_<ContainerAllocator> Type;

  ChairStateServiceRequest_()
    : isRequest(false)
    , state(0)  {
    }
  ChairStateServiceRequest_(const ContainerAllocator& _alloc)
    : isRequest(false)
    , state(0)  {
    }



   typedef uint8_t _isRequest_type;
  _isRequest_type isRequest;

   typedef uint8_t _state_type;
  _state_type state;




  typedef boost::shared_ptr< ::coalas_pkg::ChairStateServiceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::coalas_pkg::ChairStateServiceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ChairStateServiceRequest_

typedef ::coalas_pkg::ChairStateServiceRequest_<std::allocator<void> > ChairStateServiceRequest;

typedef boost::shared_ptr< ::coalas_pkg::ChairStateServiceRequest > ChairStateServiceRequestPtr;
typedef boost::shared_ptr< ::coalas_pkg::ChairStateServiceRequest const> ChairStateServiceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::coalas_pkg::ChairStateServiceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::coalas_pkg::ChairStateServiceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace coalas_pkg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'coalas_pkg': ['/home/user/catkin_ws/src/coalas_pkg/msg'], 'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::coalas_pkg::ChairStateServiceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::coalas_pkg::ChairStateServiceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::coalas_pkg::ChairStateServiceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::coalas_pkg::ChairStateServiceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::coalas_pkg::ChairStateServiceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::coalas_pkg::ChairStateServiceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::coalas_pkg::ChairStateServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ee56d3dca19715276a7a10f666663fd3";
  }

  static const char* value(const ::coalas_pkg::ChairStateServiceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xee56d3dca1971527ULL;
  static const uint64_t static_value2 = 0x6a7a10f666663fd3ULL;
};

template<class ContainerAllocator>
struct DataType< ::coalas_pkg::ChairStateServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "coalas_pkg/ChairStateServiceRequest";
  }

  static const char* value(const ::coalas_pkg::ChairStateServiceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::coalas_pkg::ChairStateServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool isRequest\n\
uint8 state\n\
";
  }

  static const char* value(const ::coalas_pkg::ChairStateServiceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::coalas_pkg::ChairStateServiceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.isRequest);
      stream.next(m.state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct ChairStateServiceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::coalas_pkg::ChairStateServiceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::coalas_pkg::ChairStateServiceRequest_<ContainerAllocator>& v)
  {
    s << indent << "isRequest: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.isRequest);
    s << indent << "state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COALAS_PKG_MESSAGE_CHAIRSTATESERVICEREQUEST_H
