// Generated by gencpp from file coalas_pkg/ChairState.msg
// DO NOT EDIT!


#ifndef COALAS_PKG_MESSAGE_CHAIRSTATE_H
#define COALAS_PKG_MESSAGE_CHAIRSTATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace coalas_pkg
{
template <class ContainerAllocator>
struct ChairState_
{
  typedef ChairState_<ContainerAllocator> Type;

  ChairState_()
    : header()
    , chairState(0)
    , isReply(false)  {
    }
  ChairState_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , chairState(0)
    , isReply(false)  {
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _chairState_type;
  _chairState_type chairState;

   typedef uint8_t _isReply_type;
  _isReply_type isReply;




  typedef boost::shared_ptr< ::coalas_pkg::ChairState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::coalas_pkg::ChairState_<ContainerAllocator> const> ConstPtr;

}; // struct ChairState_

typedef ::coalas_pkg::ChairState_<std::allocator<void> > ChairState;

typedef boost::shared_ptr< ::coalas_pkg::ChairState > ChairStatePtr;
typedef boost::shared_ptr< ::coalas_pkg::ChairState const> ChairStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::coalas_pkg::ChairState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::coalas_pkg::ChairState_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace coalas_pkg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'coalas_pkg': ['/home/user/catkin_ws/src/coalas_pkg/msg'], 'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::coalas_pkg::ChairState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::coalas_pkg::ChairState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::coalas_pkg::ChairState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::coalas_pkg::ChairState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::coalas_pkg::ChairState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::coalas_pkg::ChairState_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::coalas_pkg::ChairState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "770dd4f310939c7d3448eaff5bc868c9";
  }

  static const char* value(const ::coalas_pkg::ChairState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x770dd4f310939c7dULL;
  static const uint64_t static_value2 = 0x3448eaff5bc868c9ULL;
};

template<class ContainerAllocator>
struct DataType< ::coalas_pkg::ChairState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "coalas_pkg/ChairState";
  }

  static const char* value(const ::coalas_pkg::ChairState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::coalas_pkg::ChairState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header  \n\
uint8 chairState\n\
bool isReply\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::coalas_pkg::ChairState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::coalas_pkg::ChairState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.chairState);
      stream.next(m.isReply);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct ChairState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::coalas_pkg::ChairState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::coalas_pkg::ChairState_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "chairState: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.chairState);
    s << indent << "isReply: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.isReply);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COALAS_PKG_MESSAGE_CHAIRSTATE_H
