// Generated by gencpp from file coalas_pkg/ChairStateServiceResponse.msg
// DO NOT EDIT!


#ifndef COALAS_PKG_MESSAGE_CHAIRSTATESERVICERESPONSE_H
#define COALAS_PKG_MESSAGE_CHAIRSTATESERVICERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace coalas_pkg
{
template <class ContainerAllocator>
struct ChairStateServiceResponse_
{
  typedef ChairStateServiceResponse_<ContainerAllocator> Type;

  ChairStateServiceResponse_()
    : responseState(0)  {
    }
  ChairStateServiceResponse_(const ContainerAllocator& _alloc)
    : responseState(0)  {
    }



   typedef uint8_t _responseState_type;
  _responseState_type responseState;




  typedef boost::shared_ptr< ::coalas_pkg::ChairStateServiceResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::coalas_pkg::ChairStateServiceResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ChairStateServiceResponse_

typedef ::coalas_pkg::ChairStateServiceResponse_<std::allocator<void> > ChairStateServiceResponse;

typedef boost::shared_ptr< ::coalas_pkg::ChairStateServiceResponse > ChairStateServiceResponsePtr;
typedef boost::shared_ptr< ::coalas_pkg::ChairStateServiceResponse const> ChairStateServiceResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::coalas_pkg::ChairStateServiceResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::coalas_pkg::ChairStateServiceResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace coalas_pkg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'coalas_pkg': ['/home/user/catkin_ws/src/coalas_pkg/msg'], 'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::coalas_pkg::ChairStateServiceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::coalas_pkg::ChairStateServiceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::coalas_pkg::ChairStateServiceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::coalas_pkg::ChairStateServiceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::coalas_pkg::ChairStateServiceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::coalas_pkg::ChairStateServiceResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::coalas_pkg::ChairStateServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3892965fcb2826d6d118c501ca5b7352";
  }

  static const char* value(const ::coalas_pkg::ChairStateServiceResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3892965fcb2826d6ULL;
  static const uint64_t static_value2 = 0xd118c501ca5b7352ULL;
};

template<class ContainerAllocator>
struct DataType< ::coalas_pkg::ChairStateServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "coalas_pkg/ChairStateServiceResponse";
  }

  static const char* value(const ::coalas_pkg::ChairStateServiceResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::coalas_pkg::ChairStateServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 responseState\n\
\n\
";
  }

  static const char* value(const ::coalas_pkg::ChairStateServiceResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::coalas_pkg::ChairStateServiceResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.responseState);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct ChairStateServiceResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::coalas_pkg::ChairStateServiceResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::coalas_pkg::ChairStateServiceResponse_<ContainerAllocator>& v)
  {
    s << indent << "responseState: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.responseState);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COALAS_PKG_MESSAGE_CHAIRSTATESERVICERESPONSE_H
