// Generated by gencpp from file coalas_pkg/ChairStateService.msg
// DO NOT EDIT!


#ifndef COALAS_PKG_MESSAGE_CHAIRSTATESERVICE_H
#define COALAS_PKG_MESSAGE_CHAIRSTATESERVICE_H

#include <ros/service_traits.h>


#include <coalas_pkg/ChairStateServiceRequest.h>
#include <coalas_pkg/ChairStateServiceResponse.h>


namespace coalas_pkg
{

struct ChairStateService
{

typedef ChairStateServiceRequest Request;
typedef ChairStateServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ChairStateService
} // namespace coalas_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::coalas_pkg::ChairStateService > {
  static const char* value()
  {
    return "42126302442a5f2c473cd1143313390c";
  }

  static const char* value(const ::coalas_pkg::ChairStateService&) { return value(); }
};

template<>
struct DataType< ::coalas_pkg::ChairStateService > {
  static const char* value()
  {
    return "coalas_pkg/ChairStateService";
  }

  static const char* value(const ::coalas_pkg::ChairStateService&) { return value(); }
};


// service_traits::MD5Sum< ::coalas_pkg::ChairStateServiceRequest> should match 
// service_traits::MD5Sum< ::coalas_pkg::ChairStateService > 
template<>
struct MD5Sum< ::coalas_pkg::ChairStateServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::coalas_pkg::ChairStateService >::value();
  }
  static const char* value(const ::coalas_pkg::ChairStateServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::coalas_pkg::ChairStateServiceRequest> should match 
// service_traits::DataType< ::coalas_pkg::ChairStateService > 
template<>
struct DataType< ::coalas_pkg::ChairStateServiceRequest>
{
  static const char* value()
  {
    return DataType< ::coalas_pkg::ChairStateService >::value();
  }
  static const char* value(const ::coalas_pkg::ChairStateServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::coalas_pkg::ChairStateServiceResponse> should match 
// service_traits::MD5Sum< ::coalas_pkg::ChairStateService > 
template<>
struct MD5Sum< ::coalas_pkg::ChairStateServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::coalas_pkg::ChairStateService >::value();
  }
  static const char* value(const ::coalas_pkg::ChairStateServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::coalas_pkg::ChairStateServiceResponse> should match 
// service_traits::DataType< ::coalas_pkg::ChairStateService > 
template<>
struct DataType< ::coalas_pkg::ChairStateServiceResponse>
{
  static const char* value()
  {
    return DataType< ::coalas_pkg::ChairStateService >::value();
  }
  static const char* value(const ::coalas_pkg::ChairStateServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COALAS_PKG_MESSAGE_CHAIRSTATESERVICE_H
