// Generated by gencpp from file coalas_pkg/ChairOutput.msg
// DO NOT EDIT!


#ifndef COALAS_PKG_MESSAGE_CHAIROUTPUT_H
#define COALAS_PKG_MESSAGE_CHAIROUTPUT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace coalas_pkg
{
template <class ContainerAllocator>
struct ChairOutput_
{
  typedef ChairOutput_<ContainerAllocator> Type;

  ChairOutput_()
    : header()
    , joy_speed_output(0)
    , joy_turn_output(0)
    , left_encoder_pos(0)
    , right_encoder_pos(0)
    , sensdor_data()  {
      sensdor_data.assign(0);
  }
  ChairOutput_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , joy_speed_output(0)
    , joy_turn_output(0)
    , left_encoder_pos(0)
    , right_encoder_pos(0)
    , sensdor_data()  {
      sensdor_data.assign(0);
  }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _joy_speed_output_type;
  _joy_speed_output_type joy_speed_output;

   typedef uint8_t _joy_turn_output_type;
  _joy_turn_output_type joy_turn_output;

   typedef uint8_t _left_encoder_pos_type;
  _left_encoder_pos_type left_encoder_pos;

   typedef uint8_t _right_encoder_pos_type;
  _right_encoder_pos_type right_encoder_pos;

   typedef boost::array<uint8_t, 11>  _sensdor_data_type;
  _sensdor_data_type sensdor_data;




  typedef boost::shared_ptr< ::coalas_pkg::ChairOutput_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::coalas_pkg::ChairOutput_<ContainerAllocator> const> ConstPtr;

}; // struct ChairOutput_

typedef ::coalas_pkg::ChairOutput_<std::allocator<void> > ChairOutput;

typedef boost::shared_ptr< ::coalas_pkg::ChairOutput > ChairOutputPtr;
typedef boost::shared_ptr< ::coalas_pkg::ChairOutput const> ChairOutputConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::coalas_pkg::ChairOutput_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::coalas_pkg::ChairOutput_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace coalas_pkg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'coalas_pkg': ['/home/user/catkin_ws/src/coalas_pkg/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::coalas_pkg::ChairOutput_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::coalas_pkg::ChairOutput_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::coalas_pkg::ChairOutput_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::coalas_pkg::ChairOutput_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::coalas_pkg::ChairOutput_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::coalas_pkg::ChairOutput_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::coalas_pkg::ChairOutput_<ContainerAllocator> >
{
  static const char* value()
  {
    return "198ba088e7494b92607b05fbbfe58e4f";
  }

  static const char* value(const ::coalas_pkg::ChairOutput_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x198ba088e7494b92ULL;
  static const uint64_t static_value2 = 0x607b05fbbfe58e4fULL;
};

template<class ContainerAllocator>
struct DataType< ::coalas_pkg::ChairOutput_<ContainerAllocator> >
{
  static const char* value()
  {
    return "coalas_pkg/ChairOutput";
  }

  static const char* value(const ::coalas_pkg::ChairOutput_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::coalas_pkg::ChairOutput_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
uint8 joy_speed_output\n\
uint8 joy_turn_output\n\
uint8 left_encoder_pos\n\
uint8 right_encoder_pos\n\
uint8[11] sensdor_data\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::coalas_pkg::ChairOutput_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::coalas_pkg::ChairOutput_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.joy_speed_output);
      stream.next(m.joy_turn_output);
      stream.next(m.left_encoder_pos);
      stream.next(m.right_encoder_pos);
      stream.next(m.sensdor_data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct ChairOutput_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::coalas_pkg::ChairOutput_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::coalas_pkg::ChairOutput_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "joy_speed_output: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.joy_speed_output);
    s << indent << "joy_turn_output: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.joy_turn_output);
    s << indent << "left_encoder_pos: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.left_encoder_pos);
    s << indent << "right_encoder_pos: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.right_encoder_pos);
    s << indent << "sensdor_data[]" << std::endl;
    for (size_t i = 0; i < v.sensdor_data.size(); ++i)
    {
      s << indent << "  sensdor_data[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.sensdor_data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // COALAS_PKG_MESSAGE_CHAIROUTPUT_H
